### PR TITLE
Feature/template update

### PR DESCRIPTION
**Pull request by henrynoowah**
## Description

Suggestion for new Issue template
- API request from Frontend Team -> Backend team
- 📍 Frontend team regularly requests updates and fixes of APIs to backend
- I am suggesting a request from similar to the backlog item that we used to use in Azure Dev

<br>
Example:

- https://dev.azure.com/icloudhospital/CloudHospital/_backlogs/backlog/Backend%20development/Epics/?workitem=6618
- https://dev.azure.com/icloudhospital/CloudHospital/_backlogs/backlog/Backend%20development/Epics/?workitem=6738
- https://dev.azure.com/icloudhospital/CloudHospital/_backlogs/backlog/Backend%20development/Epics/?workitem=6788

## Pull request type

- [x] Other (please describe): Issue_template suggestion

## To reviewers
- It is my first time writing a template issue for .github
- please correct me if I made any mistakes that might ruin issue template set up

### CODE REVIEW

**Review by ggghhh27 — APPROVED** [review]
👍

**Comment by akagaeng** [comment]
* request_API -> request_api 다른 파일들과 같이 파일명을 소문자로 통일하면 좋겠어요
* 파일 확장자를 .md 로 변경해주세요 😄

**Review by JulietKilo2 — APPROVED** [review]
Looks very good to me

**Comment by henrynoowah** [comment]
@akagaeng 파일을 가져오면서 md 파일형식이 깨진 줄 확인 못했습니다 😓 네이밍 컨벤션도 고려하여 수정 후 다시 올렸습니다!

**Pull request merged**
